### ISSUE TITLE
Not able to read Tombstoned messages

### ISSUE THREAD

**Issue by JohnDLe** [ycherkes/multi-schema-avro-desrializer#4]
Deserializing fails on a message with a NULL value.

**Comment by ycherkes** [comment]
Hey @JohnDLe,
Thanks for reporting, I'll take a look.

**Comment by ycherkes** [comment]
Could you provide me with more info?
Can this message be successfully deserialized with GenericAvroDeserializer or AvroDeserializer<>?
It will be beneficial to create a unit test based on this one.

**Comment by ycherkes** [comment]
I would ask you to build [this branch](https://github.com/ycherkes/multi-schema-avro-desrializer/tree/4-not-able-to-read-tombstoned-messages) and verify if it works for you.
TIA

**Comment by JohnDLe** [comment]
The branch you created didn't work. The error message "Local: Value deserialization error" with inner exception message "Expecting the data framing of length 5 bytes or more but total data size is 0 bytes".

When the producer tombstone a message the code looks like this:

using (var tombstoneProducer = new ProducerBuilder<int, Null>(schemaRegistryConfig)
                .SetKeySerializer(new AvroSerializer<int>(schemaRegistry))
                .SetValueSerializer(Serializers.Null)
                .Build())
{
     await tombstoneProducer.ProduceAsync("SomeTopic", new Message<int, Null> { Key = id, Value = null });
}

**Comment by JohnDLe** [comment]
Updating DeserializeAsync method works.

public async Task<ISpecificRecord> DeserializeAsync(ReadOnlyMemory<byte> data, bool isNull, SerializationContext context)
        {
            if (data.Length == 0 && isNull)
            {
                return null;
            }

            var deserializer = await GetDeserializer(data).ConfigureAwait(continueOnCapturedContext: false);

            return deserializer == null ? null : await deserializer.DeserializeAsync(data, isNull, context).ConfigureAwait(continueOnCapturedContext: false);
        }

**Comment by ycherkes** [comment]
Hello sir, 
I do not quite understand the root of the problem: if the value of the message is always NULL, why just don't use:

`using var consumer = new ConsumerBuilder<int, Ignore>(consumerConfig).Build();`

Because the error you mentioned is a part of a message validation.

**Comment by JohnDLe** [comment]
The message value is not always null.  It is only null when the message value is Tombstoned.  

Here is the use case, Message<int, User>() is publish to a Topic.  If an only if a user was sent by mistake or "Deleted" in the database would we have to "Tombstone" the message sent with a Message<int, Null>.  The Key is the UserId.

Consumers that originally ingest the message and saved the User to their own datastore will receive a tombstone message and know to delete the User from their datastore that matches the UserId.  

So from a consumer perspective, they don't know when they'll receive a message with a User or a Null value.  They just know if the message value is null, it means the User has been tombstoned and that the publisher is conveying that the User is no longer existing in the source system.

**Comment by ycherkes** [comment]
Aha, got it.
So, I'll add the allowNulls argument to the deserializer.

**Comment by ycherkes** [comment]
The MR has been merged and published as version 1.0.4.
Could you please verify if it works as expected?

**Comment by JohnDLe** [comment]
I have tested version 1.0.4 and it works as expected.  Thank you!

**Comment by ycherkes** [comment]
Thank you too!
